import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const bungee = localFont({
  src: "../assets/fonts/Bungee-Regular.ttf",
  variable: "--font-bungee",
  weight: "100 900",
});


const geist_Mono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist",
  weight: "100 900",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Byte-Bandit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bungee.variable} ${geist_Mono.variable}` }>
        {children}
      </body>
    </html>
  );
}
